version: '3.4'

services:
  testcloud:
    image: testcloud
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
  
  db: 
    image: mysql:5.7
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=management 
    volumes: 
      - ./mysql-data:/var/lib/mysql
