version: '3.8'

services:
  testcloud:
    image: testcloud
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db"]
      interval: 10s
      retries: 5
  
  db: 
    image: mysql:5.7
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=management 
    volumes: 
      - ./mysql-data:/var/lib/mysql
